### ISSUE TITLE
Skipped blocks in the explorer view during sync

### ISSUE THREAD

**Issue by coka** [tari-project/blockchain-explorer-api#40]
Not sure if this is a FE or BE issue.

It looks like blocks are being skipped if more than one new block appears during a sync. This might very well be a non-issue (because I'm guessing prod will rarely fetch more than one block per sync), but in case it is, we might want to fix this.

If you guys were already aware of the issue, maybe you know where I can start looking?

<img width="1818" alt="image" src="https://user-images.githubusercontent.com/10366797/90988430-fe245000-e592-11ea-8769-a39e25500551.png">

**Comment by Krakaw** [comment]
This was intentional, when you're syncing from block 0 (after a re-org of possibly hundreds of blocks) it would spam all the client connections. This just smooths the flow. Since the block time is 2 minutes, there should rarely be more than 1 block per sync.

**Comment by coka** [comment]
OK, gonna close. :+1:

If this ever becomes an issue, we can create different WebSocket messages for "new block", "(up to N) new blocks", and "just fetch the blocks again because there are >N".
